# Generated by Django 3.1.4 on 2021-02-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=5000)),
                ('attendees', models.ManyToManyField(to='myblogs.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogs.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TimeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('voters', models.ManyToManyField(to='myblogs.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('answers', models.ManyToManyField(to='myblogs.Answer')),
                ('comments', models.ManyToManyField(to='myblogs.Comment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogs.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=5000)),
                ('attendees', models.ManyToManyField(to='myblogs.Profile')),
                ('classes', models.ManyToManyField(to='myblogs.Classes')),
                ('comments', models.ManyToManyField(to='myblogs.Comment')),
                ('questions', models.ManyToManyField(to='myblogs.Questions')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='comments',
            field=models.ManyToManyField(to='myblogs.Comment'),
        ),
        migrations.AddField(
            model_name='classes',
            name='times',
            field=models.ManyToManyField(to='myblogs.TimeChoice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='comments',
            field=models.ManyToManyField(to='myblogs.Comment'),
        ),
        migrations.AddField(
            model_name='answer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogs.profile'),
        ),
    ]
